# Generated by Django 3.2.7 on 2021-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
